resources:
  pipelines:
  - pipeline: firstpipeline # Name of the pipeline resource.
    source: daegon0130.nest-basic # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run pipeline when any run of daegon0130.nest-basic completes
steps:
- bash: echo "runs after daegon0130.nest-basic completes"
